version: 2
notify:
 webhooks:
   - url: https://Claraio-circledisc.herokuapp.com/hooks/circleci
jobs:
  build:
    docker:
      - image: chinodesuuu/ci-amethyst:latest  
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Clara (Nightly - Alpine Nightly)
          command: docker build -t chinodesuuu/clara:alpine-nightly ./Clara-Alpine-Nightly          
      - run:
          name: Build Clara (Nightly - Alpine)
          command: docker build -t chinodesuuu/clara:alpine ./Clara-Alpine            
          
      - run:
          name: Build Clara (Ubuntu)
          command: docker build -t chinodesuuu/clara:ubuntu ./Clara-Ubuntu
      - run:
          name: Build Clara (Ubuntu)
          command: docker build -t chinodesuuu/clara:ubuntu-nightly ./Clara-Ubuntu-Nightly
  deploy:
    docker:
      - image: chinodesuuu/ci-amethyst:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Clara (Nightly - Alpine Nightly)
          command: docker build -t chinodesuuu/clara:alpine-nightly ./Clara-Alpine-Nightly          
      - run:
          name: Build Clara (Alpine)
          command: docker build -t chinodesuuu/clara:alpine ./Clara-Alpine            
      - run:
          name: Build Clara (Ubuntu)
          command: docker build -t chinodesuuu/clara:ubuntu ./Clara-Ubuntu
      - run:
          name: Build Clara (Nightly - Ubuntu)
          command: docker build -t chinodesuuu/clara:ubuntu-nightly ./Clara-Ubuntu-Nightly
      - run:
          name: Docker Push (Clara Ubuntu)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/clara:ubuntu
      - run:
          name: Docker Push (Clara Ubuntu Nightly)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/clara:ubuntu-nightly
      - run:
          name: Docker Push (Clara Alpine)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/clara:alpine
      - run:
          name: Docker Push (Clara Alpine Nightly)
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push chinodesuuu/clara:alpine-nightly                    
          
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only: master
    jobs:
      - deploy
  build-n-deploy: 
    jobs:
      - build
      - deploy